# Generated by Django 4.1.2 on 2022-11-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPixel104', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Estudiante',
        ),
    ]
