# Generated by Django 4.1.2 on 2022-11-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPixel104', '0002_rename_estudiantes_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
